name: Build APK
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2
      with:
        lfs: true
        
    - name: Restore LFS cache
      uses: actions/cache@v2
      id: lfs-cache
      with:
        path: .git/lfs
        key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

    - name: Git LFS Pull
      run: |
        git lfs pull
        git add .
        git reset --hard
        
    - name: Restore Library cache
      uses: actions/cache@v2
      with:
        path: Library
        key: Library-PKTKR-VR-Android
        restore-keys: |
          Library-build-
          Library-
          
    - name: Build Unity
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
      uses: game-ci/unity-builder@v2
      with:
        targetPlatform: Android
        buildsPath: Builds
        
    - uses: actions/upload-artifact@v2
      with:
        name: Build
        path: Builds/
