name: CheckMerge

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: 
      - ready_for_review
      - review_requested

jobs:

  buildAndroid:
    runs-on: ubuntu-latest
    steps:
    - run: |
          echo building...
          
  if_merged:
      needs: buildAndroid
      runs-on: ubuntu-latest
      steps:
      - run: |
          echo All checks are fine. The PR can be merged ✅
          
  if_notMerged:
      if: github.event.pull_request.merged == false
      runs-on: ubuntu-latest
      steps:
      - run: |
          echo There were errors in the build, PR should NOT be merged ❌
